
trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- name: demo
  value: mydemo

parameters:
  - name: env
    displayName: Environment
    type: string
    values:
      - dev
      - prod
      - test
      - train
    default: dev

stages:
- stage: Stage1
  jobs:
  - job: BJ
    displayName: Build Job
    steps:
    - script: echo build

  - job: PJ
    displayName: Package Job
    steps:
    - script: echo Package
    dependsOn: BJ

  - job: DJ
    displayName: Deploy Job
    steps:
    - script: echo Deploy
    dependsOn: PJ