trigger:
- master

resources:
  containers:
  - container: mycontainer
    image: ubuntu:18.04

variables:
- group: docker
- name: myvar
  value: myvalue

stages:
- stage:
  displayName: stage1
  variables:
    myvariable: value1 # this var is only available within this stage
  jobs:
  - job: job1
    variables:
      myvariable: value2 # this var is only available within this job
    steps:
    - script: "echo $(docker.username)"
