
trigger:
- master

pool:
  vmImage: ubuntu-latest
 
jobs:
- job: BJ
  displayName: Build Job
  steps:
  - script: echo build

- job: PJ
  displayName: Package Job
  steps:
    - script: echo Package

- job: DJ
  displayName: Deploy Job
  steps:
    - script: echo Deploy