trigger:
- master

resources:
  containers:
  - container: mycontainer
    image: ubuntu:18.04

variables:
  myvariable: value # this var is available to all jobs in all stages

stages:
- stage:
  displayName: stage1
  variables:
    myvariable: value1 # this var is only available within this stage
  jobs:
  - job: job1
    variables:
      myvariable: value2 # this var is only available within this job
    steps:
    - script: echo $(myvariable)
