trigger:
- master

resources:
  containers:
  - container: mycontainer
    image: ubuntu:18.04

steps:
- script: echo "Hello from host"
  target: host
- script: echo "Hello from inside of container" && printenv
  target: mycontainer
