stages:
- stage: Test
  jobs:
  - job: job1
    steps:
      - script: echo Test
  
- stage: Test1
  jobs:
    - job: Test1
      steps:
        - script: echo "Test1 - this stage runs after Test"
  dependsOn: Test
  
- stage: Test2
  jobs:
    - job: Test2
      steps:
        - script: echo "Test2 - this stage runs in parallel with Test1, after Test"
  dependsOn: Test
  
- stage: TestMultiDependencies
  jobs:
    - job: TestMultiDependencies
      steps:
        - script: echo "TestMultiDependencies - this stage runs after Test1 and Test2"
  dependsOn:
  - Test1
  - Test2
  
- stage: TestNoDependency
  dependsOn: []
  jobs:
    - job: TestNoDependency
      steps:
        - script: echo "TestNoDependency - this stage runs in parallel with Test"