
trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- name: demo
  value: mydemo

parameters:
  - name: env
    displayName: Environment
    type: string
    values:
      - dev
      - prod
      - test
      - train
    default: dev

stages:
- stage: BuildStage
  jobs:
  - job: BJ
    displayName: Build Job
    steps:
    - script: echo build

- stage: PackageStage
  dependsOn: BJ
  jobs:
  - job: PJ
    displayName: Package Job
    steps:
    - script: echo Package

- stage: DeployStage
  dependsOn: PJ
  jobs:
  - job: DJ
    displayName: Deploy Job
    steps:
    - script: echo Deploy