
trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  global_variable: myglogalvar # this var is available to all jobs in all stages
 
stages:
- stage: stage1
  displayName: stage1
  variables:
    stage_variable: mystagevar1 # this var is only available within this stage
  jobs:
  - job: job1
    variables:
      job_variable: myjobvar1 # this var is only available within this job
    steps:
    - script: echo $(global_variable)
    - script: echo $(stage_variable)
    - script: echo $(job_variable)