trigger:
- master

resources:
  containers:
  - container: mycontainer
    image: ubuntu:18.04

variables:
- group: docker
- name: myvar
  value: myvalue

stages:
- stage:
  displayName: stage1
  jobs:
  - job: job1
    steps:
    - script: echo $MY_SECRET
      env:
        MY_SECRET: $(mysecretvar)
        
